import mutations from "./mautations.js";
import actions from "./actions.js";
import getters from "./getters.js";
export default {
    namespaced: true,
    state() {
        return {
            coaches: [{
                    id: "c1",
                    job: "Fornt-end Developer",
                    name: "Mohamed Mujahid",
                    jobFilter: "frontend",
                    image: "https://randomuser.me/api/portraits/men/2.jpg",
                    age: 21,
                    email: "mohamed.mojahead@gmail.com",
                    location: "Giza, Egypt",
                    website: "https://webdesginer.me",
                    phoneOne: "+2001151547569",
                    phoneTow: "+2001559079068",
                    exp: "1+ year",
                    rate: 4,
                    freelance: true,
                    disc: "hello, i'm a profishional Front-end Developer With 1+ year Exeprince let me be your Coach in your Learning Journy I will Make you a Dragon Expert Like Me.",
                },
                {
                    id: "c2",
                    name: "Osmam Mohamed",
                    job: "Full-Stack Developer",
                    jobFilter: "fullstack",
                    image: "https://randomuser.me/api/portraits/men/3.jpg",
                    age: 34,
                    email: "osama.mohamed@elzero.org",
                    location: "Cairo, Egypt",
                    website: "https://elzero.org",
                    phoneOne: "not-available",
                    phoneTow: "not-available",
                    exp: "20+ years",
                    rate: 5,
                    freelance: false,
                    disc: "dolor set amit! lorem absoum dolor set amit! absoum dolor set amit! lorem absoum dolor set amit! lorem absoum dolor set amit absoum dolor set amit! lorem absoum dolor set amit! lorem absoum dolor set lorem absoum dolor set amit!lorem absoum dolor set amit! lorem absoum amit! lorem absoum dolor set",
                },
                {
                    id: "c3",
                    name: "Omar Mahmoud",
                    job: "back-end Developer",
                    jobFilter: "backend",
                    image: "https://randomuser.me/api/portraits/men/5.jpg",
                    age: 22,
                    email: "omarmahmoud1999@gmail.com",
                    location: "monofia, Egypt",
                    website: "unavailable",
                    phoneOne: "not-available",
                    phoneTow: "not-available",
                    exp: "2+ years",
                    rate: 4,
                    freelance: true,
                    disc: "dolor set amit! lorem absoum dolor set amit! absoum dolor set amit! lorem absoum dolor set amit! lorem absoum dolor set amit absoum dolor set amit! lorem absoum dolor set amit! lorem absoum dolor set lorem absoum dolor set amit!lorem absoum dolor set amit! lorem absoum amit! lorem absoum dolor set",
                },
                {
                    id: "c4",
                    name: "Haidy Yhia",
                    job: "UI/UX Desginer",
                    jobFilter: "uiux",
                    image: "https://randomuser.me/api/portraits/women/8.jpg",
                    age: 22,
                    email: "haidy.yhia@gmail.com",
                    location: "Helwan, Egypt",
                    website: "unavailable",
                    phoneOne: "not-available",
                    phoneTow: "not-available",
                    exp: "2+ years",
                    rate: 5,
                    freelance: true,
                    disc: "dolor set amit! lorem absoum dolor set amit! absoum dolor set amit! lorem absoum dolor set amit! lorem absoum dolor set amit absoum dolor set amit! lorem absoum dolor set amit! lorem absoum dolor set lorem absoum dolor set amit!lorem absoum dolor set amit! lorem absoum amit! lorem absoum dolor set",
                },
            ],
        };
    },
    mutations,
    actions,
    getters,
};